apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

      containers:
      - name: httpd

        env:
        - name: NODE_NAME
          value: "infovista-historical-ingestion"        
        
        image: php:8.1.0RC2-apache

        imagePullPolicy: IfNotPresent
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #       - cp
        #       - -a
        #       - /tmp/logstash/pipeline/.
        #       - /usr/share/logstash/pipeline/

        ports:
        - containerPort: 80
          name: tcp-0
          protocol: TCP

        securityContext:
          # capabilities:
          #   add:
          #   - NET_BIND_SERVICE
          # procMount: Default

        volumeMounts:
          - mountPath: /var/www/html
            name: www
            # subPath: logstash.conf

            


      volumes:
        - name: www
          configMap:
            name: www-configmap
            # defaultMode: 502
            # items:
            # - key: logstash.conf
            #   path: logstash.conf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web-http
  namespace: default
spec:
  type: NodePort
  selector:
    app: web 
  ports:
  - name: web-http-80
    nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 80

      # nso-pp-w-04.nso.int.bell.ca
      # 32666


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: web-ingress
  namespace: default
spec:
  ingressClassName: public
  rules:
  - host: web.liberty.local
    http:
      paths:
      - backend:
          service:
            name: web-http
            port:
              number: 80
        path: /
        pathType: Exact


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-configmap
  namespace: default
data:
  index.php: |-
    <?php
      echo "Hello!";
    ?>
